DROP TABLE IF EXISTS todos;

CREATE TABLE todos
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    task       VARCHAR(255)                        NOT NULL,
    status     TINYINT   DEFAULT 0                 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
